---
title: "contact tracing"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Contact tracing

```{r}
library(deSolve)
```

```{r}
seir2_model <- function(t,state_t0,param) {
    with(as.list(c(state_t0, param)), {

        # population size
        N <- S+E+Ece+Eci+Ih+Iu+Ice+Ici+H+R

        # derived parameters
        pe <- tau/(tau + Th)*exp(-delta/tau)
        pei <- pe
        pee <- pe

        # differential equations
        dS <- -(S/N)*beta*(Ih + Iu) - beta*(S/N)*Ici - 
            betam*(S/N)*Ice
        dE <- (S/N)*beta*Iu + (1-phi)*(S/N)*beta*Ih + 
            (1-phi)*beta*(S/N)*Ici + (1-phi)*betam*(S/N)*Ice - (1/tau)*E
        dEce <- pe*phi*beta*S*Ih + pei*phi*beta*S*Ici + 
            pee*phi*betam*S*Ice - (1/tau)*Ece
        dEci <- pe*(1-phi)*beta*S*Ih + pei*(1-phi)*beta*S*Ici +
            pee*(1-phi)*betam*S*Ice - (1/tau)*Eci
        dIh <- (rho/tau)*E - (1/Th)*Ih
        dIu <- ((1-rho)/tau)*E - (1/Tu)*Iu
        dIce <- (1/tau)*Ece - (1/Tm)*Ice
        dIci <- (1/tau)*Eci - (1/Ti)*Ici
        dH <- (1/Th)*Ih
        dR <-  (1/Tu)*Iu + (1/Tm)*Ice + (1/Ti)*Ici

        # return
        list(c(dS,dE,dEce,dEci,dIh,dIu,dIce,dIci,dH,dR))
    })
}
```


```{r}
x0 <- c(S=1000,E=10,Ece=0,Eci=0,Ih=0,Iu=0,Ice=0,Ici=0,H=0,R=0)
params <- list(tau=5,Th=5,beta=0.1,delta=0,betam=0.1,phi=0.5,
               rho=0.5,Tu=5,Tm=5,Ti=5)
ode(y = x0,times = 1:100,func = seir2_model, parms = params)
```

