---
title: "Available models in COVOID"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Models}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(covoid)
```

All graphs created using **DiagrammR**

## Homogeneous mixing

These models assume....

### SIR model

`sir_state0` `sir_param` and `simulate_sir`

```{r}
DiagrammeR::grViz("
digraph SIR {

  graph [overlap = false,
        fontsize = 10
        rankdir = LR]

  node [shape = box,
        fontname = Helvetica,
        color='grey']

  S[label='S\nsusceptible'];
  I[label='I\ninfected'];
  R[label='R\nremoved'];

  edge [color = 'black']
  S -> I
  I -> R
}")
```

### SEIR model

`seir_state0` `seir_param` and `simulate_seir`

```{r}
DiagrammeR::grViz("
digraph SEIR {

  graph [overlap = false,
        fontsize = 10
        rankdir = LR]

  node [shape = box,
        fontname = Helvetica,
        color='grey']

  S[label='S\nsusceptible'];
  E[label='E\nexposed\n(latent period)']
  I[label='I\ninfected'];
  R[label='R\nremoved'];

  edge [color = 'black']
  S -> E
  E -> I
  I -> R
}")
```

```{r}
DiagrammeR::grViz("
digraph SEIR_inf {

  graph [overlap = false,
        fontsize = 10
        rankdir = LR]

  node [shape = box,
        fontname = Helvetica,
        color='grey']

  S[label='S\nsusceptible'];
  I[label='I\ninfected'];

  edge [color = 'red' style=dashed]
  I -> S
}")
```

### Expanded SEIR model (Moss et al (2020))

## Age structured mixing

### SIR model

`sir_c_state0` `sir_c_param` and `simulate_sir_c`



### SEIR model

`seir_c_state0` `seir_c_param` and `simulate_seir_c`

```{r,fig.cap="Age structured SEIR model. There are j=1,...J discrete age groups."}
DiagrammeR::grViz("
digraph SEIR_C {

  graph [overlap = false,
        fontsize = 10
        rankdir = LR]

  node [shape = box,
        fontname = Helvetica,
        color='grey']

  S[label=<S<SUB>j</SUB><BR/><BR/>susceptible>];
  E[label=<E<SUB>j</SUB><BR/><BR/>exposed>];
  I[label=<I<SUB>j</SUB><BR/><BR/>infected>];
  R[label=<R<SUB>j</SUB><BR/><BR/>removed>];
 
  edge [color = 'black']
  S -> E
  E -> I
  I -> R
}")
```
```{r}
DiagrammeR::grViz("
digraph SEIR_C_inf {

  graph [overlap = false,
        fontsize = 10
        rankdir = LR]

  node [shape = box,
        fontname = Helvetica,
        color='grey']

  S[label='S\nsusceptible'];
  I1[label='I1\ninfected'];
  
  node [color = 'white']
  I2[label='...'];
  
  node [shape = box,
        fontname = Helvetica,
        color='grey']
  IN[label='IN\ninfected'];


  edge [color = 'red' style=dashed]
  I1 -> S
  I2 -> S
  IN -> S
  
}")
```

