---
title: "Modelling interventions in COVOIDd"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{modelling-interventions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(COVOIDd)
library(ggplot2)
```

Define the basic reproduction number R<sub>0</sub> and effective reproduction number R<sub>t</sub> under an intervention (e.g. social distancing). Note the intervention is over a defined period rather than indefinitely. On average it reduces contact between individuals by 50% and has delayed start and end.

```{r}
R0 <- function(t) 2.5
R_effective <- add_intervention(R0,start = 5,stop = 30,c_reduce = 0.5,start_delay=10,stop_delay=10)
```

```{r,echo=FALSE,fig.width=7}
x <- 1:100
y <- sapply(1:100,R_effective)
ggplot(data.frame(x,y)) +
  geom_line(aes(x=x,y=y)) +
  coord_cartesian(ylim=c(0,3)) +
  labs(y=expression(R[t]),x="Time",title="Impact of the intervention") +
  theme_bw()
```

See the result of the intervention on the epidemic:

```{r,fig.width=7,fig.height=5}
# shared initial state
state0 <- sir_state0(S0 = 100,I0 = 1,R0 = 0)

# different parameters
param_int <- sir_param(R0 = R_effective,gamma = 0.1)
param_non <- sir_param(R0 = R0,gamma = 0.1)

# results
res_int <- simulate_sir(t = 100,state_t0 = state0,param = param_int)
res_non <- simulate_sir(t = 100,state_t0 = state0,param = param_non)

p1 <- plot(res_int,c("S","I","R"),main="Intervention") + labs(x="Time") +
  geom_ribbon(data=data.frame(y=c(0,100)),aes(xmin=5,xmax=30,y=y),fill="lightblue",alpha=0.2)
p2 <- plot(res_non,c("S","I","R"),main="No intervention") +labs(x="Time")
gridExtra::grid.arrange(p1,p2)
```




